// The bundled match catalog (web/public/catalog.json), generated by scripts/build_catalog.py
// from the Cricsheet data: every IPL season, each match's teams, date, ball count, playoff
// stage, and winner. The web app drives season + match selection entirely from this static
// file; only the ball-by-ball replay itself hits the serving API.

export interface CatalogMatch {
  id: string;
  teams: [string, string];
  date: string;
  iso: string;
  balls: number;
  innings: number;
  stage: string; // "league" | "Semi Final" | "Qualifier 1" | "Eliminator" | "Qualifier 2" | "Final" | ...
  round: number; // 0 = group stage; 1..3 = playoff rounds
  matchNo: number | null;
  winner: string;
}

export interface Season {
  season: string;
  label: string;
  champion: string;
  matches: CatalogMatch[];
}

export interface Catalog {
  competition: string;
  seasons: Season[];
}

export async function loadCatalog(signal?: AbortSignal): Promise<Catalog> {
  const res = await fetch("/catalog.json", { signal });
  if (!res.ok) throw new Error(`catalog ${res.status} ${res.statusText}`);
  return (await res.json()) as Catalog;
}

export function findMatch(catalog: Catalog, id: string): CatalogMatch | undefined {
  for (const season of catalog.seasons) {
    const match = season.matches.find((m) => m.id === id);
    if (match) return match;
  }
  return undefined;
}

// Column header for a playoff round, era-aware (Semi-Finals vs the Qualifier/Eliminator era).
export function roundLabel(round: number, matches: CatalogMatch[]): string {
  if (round === 3) return "Final";
  if (round === 2) return "Qualifier 2";
  if (round === 1)
    return matches.some((m) => m.stage === "Semi Final") ? "Semi-Finals" : "Playoffs";
  return "Group Stage";
}
